### ISSUE TITLE
qpFit help text

### ISSUE THREAD

**Issue by denispelli** [BrainardLab/mQUESTPlus#10]
1. I created a prior array for lapse rate consisting solely of 0.01. Then I called qpFit with a lowerBound lapse of 0 and an upperBound of 0.04, returning psiParamsFit(4) of 0.04. I was surprised that the fit used an extreme, not sticking to the prior. I suppose the rationale here is that the likelihood is independent of prior. However, I assumed that the coordinate space defined by the prior would apply to all estimates. It would be nice if we were explicitly told that the maximum likelihood fit returned by qpFit is continuous, not restricted to the grid defined by the prior.

2. I wish the HELP text for qpFit included an example with the optional arguments.

**Comment by DavidBrainard** [comment]
Added comments about nature of fit and pointer to demo programs that show example usage.

Closing.

**Comment by denispelli** [comment]
thanks!


[image: photo]
*Denis Pelli*
Professor of Psychology & Neural Science, New York University
+1-646-258-7524 | denis.pelli@nyu.edu | http://psych.nyu.edu/pelli/ | Skype:
denispelli <#> | http://denispelli.com
<http://www.facebook.com/denispelli>
<http://www.linkedin.com/in/denispelli/> <http://twitter.com/denispelli>
