### ISSUE TITLE
Contrast threshold not updating

### ISSUE THREAD

**Issue by lynnac** [BrainardLab/mQUESTPlus#15]
Hi there,

I am trying to use quest+ to obtain threshold, slope and lapses estimates for a basic orientation discrimination task. Participants response 'z' for 45 degree oriented Gabor and 'm' for a 135 degree oriented Gabor. After about 64 trials I would expect to have estimates of the three DVs. However, the same contrast value is presented on all 64 trials as if the outcome and contrast for each trial are not being updated using qpUpdate. 

I have attached the code. A college of mine has taken a look and we can't seem to find the issue. Any thoughts?

Andrew

[gabor_orientation_contrast.txt](https://github.com/BrainardLab/mQUESTPlus/files/2115559/gabor_orientation_contrast.txt)

**Comment by DavidBrainard** [comment]
In your call to qpInitialize, you are passing the possible threshold contrasts as 0.01:1.  In Matlab, this evaluates to a single number, 0.01.  So in essence you have told Quest+ that there is only one possible threshold level it should consider, 0.01.  This is going to limit its view of the parameter you are trying to estimate, and could well lead to the pathological behavior you observe. Looking at your code, it may be that this was a typo rather than a design choice.

Note that qpPFWeibull is set up to work in contrast units expressed in dB.  It might do fine in other units if the parameters are set up right, I haven't thought that through.

More generally, I'd recommend making a copy of qpQuestPlusCoreFunctionDemo  and modify the parameters to match your experiment, with some reasonable choice of parameters for the simulated psychometric function.  If you get that to work, then it should be fine if you plug the same things back into your experiment.  If you can't get the simulation to work properly, please post your version of the simulation here and I can take a look.

**Comment by DavidBrainard** [comment]
OK, let us know whether you get it to work, or not.  Note that in addition to the dB issue, make sure you provide qpInitialize with more than one threshold value in the parameters list.  Just four intensities in the stimulus params list also seems a bit small.

**Comment by lynnac** [comment]
Hi there,

Thanks for your help. I am getting closer. What is the range (e.g., -40:0) of the thresholds allowable? I need to specify threshold in intensity so I convert this value to and from amplitude on each trial. However, when I try to run the fit I get this error. (I don’t get this error when I simulate the data. But I may be missing something key. I’m new to the world of psychophysics.)

Error using  ^ 
Integers can only be raised to positive integral powers.

Error in qpPFWeibull (line 77)
        p1 = lapse - (guess + lapse - 1)*exp(-10^(slope*(stimParams(ii) - threshold)/20));

Error in qpLogLikelihood (line 56)
predictedProportions = qpPF(stimMat,psiParams);

Error in qpFitError (line 24)
logLikelihood = qpLogLikelihood(stimCounts,qpPF,psiParams);

Error in qpFit>@(x)qpFitError(x,stimCounts,qpPF) (line 88)
psiParams =
fmincon(@(x)qpFitError(x,stimCounts,qpPF),startingParams,[],[],[],[],p.Results.lowerBounds,p.Results.upperBounds,[],options);

Error in fmincon (line 536)
      initVals.f = feval(funfcn{3},X,varargin{:});

Error in qpFit (line 88)
psiParams =
fmincon(@(x)qpFitError(x,stimCounts,qpPF),startingParams,[],[],[],[],p.Results.lowerBounds,p.Results.upperBounds,[],options);

Error in drawgabortest (line 517)
psiParamsFit = qpFit(questData.trialData,questData.qpPF,psiParamsQuest,questData.nOutcomes,...

Caused by:
    Failure in initial objective function evaluation. FMINCON cannot continue.
 

Andrew Lynn, Sc.M
GSC Chair of Student Life
NSF Graduate Research Fellow
Developmental Cognitive Neuroscience Laboratory
Brown University
M: 540-850-4259

**Comment by DavidBrainard** [comment]
Could you please post a minimal example program that illustrates the issue you are having?  Should not contain any display code or experimental logic but rather be a relatively simple simulation.  Starting with qpQuestPlusCoreFunctionDemo and modifying to match what you are trying to do would be one good way to go about creating such an example.

**Comment by lynnac** [comment]
I’ve attached the core function demo. Basically the only really addition is that i’m converting the dB to amplitude and then back, but qpUpdate doesn’t seem to update the stim value in a way that qpFit can recognize.

Best,

Andrew Lynn, Sc.M
GSC Chair of Student Life
NSF Graduate Research Fellow
Developmental Cognitive Neuroscience Laboratory
Brown University
M: 540-850-4259

**Comment by lynnac** [comment]
i was able to get this to work by create another variable to pass directly to qpUpdate. However, when i bring this over to the actual experiment it seems that the maximum likelihood is always the upper bound of the qpFit. The ML output is the estimate of the threshold for the subject, correct?
 
Andrew Lynn, Sc.M
GSC Chair of Student Life
NSF Graduate Research Fellow
Developmental Cognitive Neuroscience Laboratory
Brown University
M: 540-850-4259

**Comment by lynnac** [comment]
Sorry to keep bugging you. One last question. I have nOutcomes (n=2) coded as incorrect, correct rather than just coding the type of response (left key, right key) is that correct?

Andrew Lynn, Sc.M
GSC Chair of Student Life
NSF Graduate Research Fellow
Developmental Cognitive Neuroscience Laboratory
Brown University
M: 540-850-4259

**Comment by DavidBrainard** [comment]
I am not seeing an attachment in the above.  But if you pass your (now working I gather) simulation I can take a look.

Not sure why it would work in simulation and not with the experiment, as long as the the subject's real threshold is within the range you're telling Quest+ about.

You are correct that the response should be coding whether the subject was incorrect or correct.
Interpretation of the passed outcomes is as documented in the help text for qpPFWeibull:
  Passing an outcome of 1 means incorrect.
  Passing an outcome of 2 means correct.
You might check that you are following this convention.

**Comment by DavidBrainard** [comment]
Is this resolved now?

**Comment by lynnac** [comment]
Hi there,

Yes I’ve made progress. If you have some suggestions for how to convert dB to contrast sensitivity, that would be helpful. But I realize this isn’t the purpose of the algorithm. 

Andrew Lynn, Sc.M
GSC Chair of Student Life
NSF Graduate Research Fellow
Developmental Cognitive Neuroscience Laboratory
Brown University
M: 540-850-4259

**Comment by DavidBrainard** [comment]
Sorry to be slow.  As it notes in the help text for qpPFWeibull:

%.                  Here the row vector is just a single number giving
%                    the stimulus contrast level in dB.  dB defined as
%                    20*log10(x).

So to do the conversion between stimulus strength x expressed as dB or just plain contrast, use:

xAsDB = 20*log10(xAsContrast);
xAsContrast = 10^(xAsDB/20);

The same conversation applies to the stimulus values and to the threshold you obtain.

Closing this issue.  Please re-open or post a new issue if you are still having problems.
