### ISSUE TITLE
Typo in utilities/qpListMaxArg.m

### ISSUE THREAD

**Issue by aernesto** [BrainardLab/mQUESTPlus#22]
Greetings, 
the function name contains a typo in the file [`utilities/qpListMaxArg.m`](https://github.com/BrainardLab/mQUESTPlus/blob/1f6a0a416e374c37047f1c5cbea09e1c1e4fdbfc/utilities/qpListMaxArg.m).

**Comment by DavidBrainard** [comment]
Thanks.  Fixed.

**Comment by aernesto** [comment]
Thanks!
