### ISSUE TITLE
going off the grid

### ISSUE THREAD

**Issue by denispelli** [BrainardLab/mQUESTPlus#9]
David said: I added a utility function qpFindNearestStimInDomain. It is not used anywhere, but might be useful if you have some custom algorithm for choosing stimuli that are not in the gridded list.  You can then do that and call this function to find out the closest you can get in a Euclidean distance set, given how you quantized the stimulus set.
            ******
The current scheme requires the user to provide a list of all possible stimuli before the run begins. During the run, QuestPlus will not accept any stimulus value off the list. For many experiments that's fine. But I wonder if there aren't real situations in which the experimenter wants to tweak the stimuli during the run and use a value off the grid. I think that it's fine for the computation of best stimulus for next trial to be confined to the grid. For that it might quantize the actual stimulus value to the grid. But QuestPlus is also serving as the record keeper for the run. Once the run is done, I want a perfect record of the stimuli and responses. If I'm a maverick experimenter who insists on using stimuli off the grid, i don't mind that the QuestPlus recommended stimuli only on the grid, but I'll be disappointed that QuestPlus has not retained an accurate record of what stimuli I showed.

There are two sides to this:
1. BENEFIT: How often does this really happen? Could mavericks just have a longer list of stimuli?
2. COST: How much trouble would it be to enhance QuestPlus to keep an accurate record of stimuli that aren't necessarily on the grid?

I admit that I haven't yet imagined a scenario where I couldn't get what I wanted by using a long list.
Denis

p.s.
I think it would help to emphasize the stimulus list. 

1. Each item on the list is assigned equal prior probability. Thus the (smoothed) probabllity density of the prior is roughly proportional to the density of stimuli in that space. Distributing the stimuli equally on a linear and log scale represent very different prior probability functions.

2. During the run, QuestPlus will only accept stimulus values on that list. So anything you might want to present must be on the list before you begin.

**Comment by DavidBrainard** [comment]
Good points about the documentation for the stimulus list.  I added a note in qpParams and also in some of the demos.

I don't think it would be hard to track actual stimuli while having QUEST+ update based on nearest gridded stimuli.  I think there is some cost in terms of simplicity, and that providing this feature might lead to surprises in some cases.  Will ponder, and probably wait until someone notes a case where this feature would be really helpful.

**Comment by DavidBrainard** [comment]
Closing this issue, as I think the current behavior is right at the level of mQUESTPlus and that a user who wants to go off the grid should do the rounding in their own code, to avoid surprises.

Happy to reconsider if it gets raised again.
